### ISSUE TITLE
New Action, right-click -> open in new tab

### ISSUE THREAD

**Issue by nas532** [chrisgurney/obsidian-note-toolbar#100]
**Description of the bug**
the right-click context menu when clicked on a button in the toolbar, it would be nice to have an option to open in a new tab. 

**Steps to reproduce**

1. right-click on button in toolbar 
2. context-menu pops up 
3. new option -> open in new tab

**Expected behavior**

**Screenshots (if you think it will help)**
_Video or a GIF would be appreciated._

**Theme links and CSS snippets (if applicable):**
_Themes and CSS snippets can affect the display of the toolbar. Include any being used here to help diagnose display issues._

**Plugin links (if applicable):**
_If you're using a specific plugin that isn't working with the toolbar, link it here._

**Desktop environment:**
 - OS: Windows 11
 - Obsidian version: 1.6.5
 - Note Toolbar version: 1.8.6 

**Mobile environment (if applicable to the issue):**
 - Device: 
 - OS: 
 - Obsidian version: 
 - Note Toolbar version: 

**Additional context**
_Add any other context about the problem here._

**Comment by chrisgurney** [comment]
@nas532 If your item is a `File` type, you should be able to use [these shortcuts](https://help.obsidian.md/User+interface/Tabs#Open+a+link) when clicking on them in the toolbar.

Would appreciate the help testing on Windows, as I don't have access to a Windows machine!

**Comment by chrisgurney** [comment]
@nas532 I'm going to close this issue as you can accomplish what you're after using the [modifier keys](https://help.obsidian.md/User+interface/Tabs#Open+a+link) when clicking on links in the toolbar.

Let me know if you have questions, or want to elaborate specifically on what you're trying to achieve. Thanks!
