### ISSUE TITLE
Sticky toolbar callout disappearing when scrolling  

### ISSUE THREAD

**Issue by okRoni** [chrisgurney/obsidian-note-toolbar#121]
**Description of the bug**

When scrolling down a note, the toolbar callout will disappear some times when passing through and image or a callout. If you scroll back up where the callout is, it will stick again, but it also disappears when scrolling down.

**Steps to reproduce**

1. In a note put a tollbar callout with the sticky property
2. Put some text below, an image and a callout (the distance between the callout and the image or callout seems to affect, so try and put it a bit far down)
3. Scroll down until the toolbar disappears

**Expected behavior**

The toolbar sticking and not disappearing 😢 

**Screenshots (if you think it will help)**
_Video or a GIF would be appreciated._

https://github.com/user-attachments/assets/5c47184b-7be7-40d8-bff9-99a3ed5e8f73

In the sandbox vault:

https://github.com/user-attachments/assets/df9f376c-cd21-40d9-9572-abb3d71bc81c

**Debug info:**
_Run "Show debug info" in Obsidian and paste it here (recommended). Alternately, fill out the sections below._

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Windows 11 Pro 10.0.22631
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Border v1.9.9
	Snippets enabled: 9
	Restricted mode: off
	Plugins installed: 22
	Plugins enabled: 21
		1: Dataview v0.5.67
		2: Excalidraw v2.3.0
		3: Kanban v2.0.51
		4: Natural Language Dates v0.6.2
		5: Style Settings v1.0.9
		6: Templater v2.4.2
		7: Quick Latex v2.6.5
		8: Calendar v1.5.10
		9: Plugin Update Tracker v1.5.2
		10: Settings Search v1.3.10
		11: Advanced Tables v0.21.0
		12: Iconize v2.14.3
		13: Share Note v0.8.15
		14: Regex Find/Replace v1.2.0
		15: Commander v0.5.1
		16: Custom File Explorer sorting v2.1.12
		17: QuickAdd v1.11.0
		18: Advanced URI v1.43.0
		19: Hide Sidebars on Window Resize v1.1.0
		20: Editor Syntax Highlight v0.1.3
		21: Note Toolbar v1.11.0

**Plugin, Theme links, and CSS snippets (if applicable):**

I used the Obsidian sandbox vault to test it, so it doesn't seem that the custom CSS is doing anything.

**Desktop environment:**
 - OS: Windows
 - Obsidian version: 1.6.7
 - Note Toolbar version: 1.11.0

**Comment by vbifonixor** [comment]
I'm pretty sure it's because obsidian virtualizes page and un-renders content of the page that is far beyond visible area so that on large files it wouldn't all be rendered and kept in memory.

I think that `sticky` and `msticky` should make the toolbar render somewhere near breadcrumbs/tabs, but I have no idea how to accomplish that

**Comment by chrisgurney** [comment]
Thanks for your thoughts!

My first attempt was going to see if the `z-index` of the toolbar is not high enough, and I just need to increase it. 

If that's not it, I'd love the help in developing a fix. 🙂

**Comment by chrisgurney** [comment]
@O-RONI I'm having problems reproducing this on macOS.

Can you please attach the markdown file you're using in your test above?

**Comment by chrisgurney** [comment]
@vbifonixor OK now I'm seeing what you're talking about: as I inspect the page as I scroll, the callout element disappears from the DOM. (The `z-index` definitely has nothing to do with it.)

I'll start by checking on the Discord to see if there's anything that might help.

**Comment by chrisgurney** [comment]
@O-RONI I received this from Liam (on the Obsidian team) which further backs up @vbifonixor 's theory above:

> [...] no, there's no way to override the editor virtualization. Codemirror manages what elements are actually rendered based on the current viewport

So, here are some thoughts on other possible future features that might support more granular toolbars in longer notes. _I'd love feedback on these._

1. Add a property to callouts that identifies a toolbar to load, in the existing `Top (fixed)` or `Below Properties` positions, when it comes within view in the editor.
    - This would mean though that the toolbar would have to be pre-defined within settings (though I'm also considering a way to pre-define toolbars in markdown, within settings, though that may be further out).
2. Ability to map toolbars to headings within a note (perhaps matched via pre-defined strings).

**Comment by O-RONI** [comment]
Well, it's a shame that it can't be fixed, but it can't be helped....

I was using callouts because it let me work with other plugins like Templater, but i think i can do some workarounds with the properties feature. The other thing great about callouts is the ability to put it in specific parts of a note, like below a certain heading. So maybe is good to keep that in mind for the possible solutions...

Anyways, thanks for the help! 🙏

**Comment by h3r** [comment]
Is not a full solution because as you say, in edit mode if you scroll too much it de renders the first lines, but seems not in view mode? Anyway in my case I use obsidian for taking short notes on my daily JIRA work. This fix its enough for me for now

```css
div.el-pre:has(div[data-callout=note-toolbar])
,  div.el-div:has(div[data-callout=note-toolbar])
, .cm-preview-code-block:has(div[data-callout=note-toolbar])
, .markdown-source-view:has(div[data-callout=note-toolbar])
{
    position: sticky !important;
    top: 0;
    z-index: 999;
    background-color: var(--background-primary);
}
```
