### ISSUE TITLE
Icons without text in the toolbar

### ISSUE THREAD

**Issue by JoKo1959** [chrisgurney/obsidian-note-toolbar#123]
Thank you for this very useful plugin. It would be nice if only the icons could be shown in the toolbar; without text. This would save space. With the text, the toolbar stretches over several lines and takes up a lot of the limited screen space on mobile. Thank you very much!

**Comment by chrisgurney** [comment]
Hello! You have a couple options for removing text:

- Labels are completely optional. Just delete your labels, or move your text into the tooltip field (so they still display in menus).
- Set the visibility using the visibility icons that let you hide labels on desktop or mobile or both.

https://github.com/chrisgurney/obsidian-note-toolbar/wiki/Creating-toolbar-items

Hope this helps!

**Comment by JoKo1959** [comment]
Thanks a lot!!

Von: Chris Gurney ***@***.***>
Gesendet: Samstag, 31. August 2024 12:59
An: chrisgurney/obsidian-note-toolbar ***@***.***>
Cc: Kornhuber, Johannes ***@***.***>; Author ***@***.***>
Betreff: Re: [chrisgurney/obsidian-note-toolbar] Icons without text in the toolbar (Issue #123)


Hello! You have a couple options for removing text:

  *   Labels are completely optional. Just delete your labels, or move your text into the tooltip field (so they still display in menus).
  *   Set the visibility using the visibility icons that let you hide labels on desktop or mobile or both.

https://github.com/chrisgurney/obsidian-note-toolbar/wiki/Creating-toolbar-items

Hope this helps!
