### ISSUE TITLE
Remove blue callout line on the left of toolbar

### ISSUE THREAD

**Issue by Saorsa32** [chrisgurney/obsidian-note-toolbar#149]
How do I remove the blue callout line on my toolbar. I am not using a callout in the note, but using one made in the app.

![Screenshot (83)](https://github.com/user-attachments/assets/dc67d0a3-f310-44a3-8c54-687f54bd5464)

**Comment by chrisgurney** [comment]
Hello! What theme or CSS snippets are you using?

**Comment by chrisgurney** [comment]
Hi @Saorsa32 can you provide more information about the theme or CSS snippets you might be using? Thanks!

**Comment by Saorsa32** [comment]
Thanks! I didn't think about the css. I figured out the problem.
