### ISSUE TITLE
Cyrilic symbols export encoding

### ISSUE THREAD

**Issue by laktiv** [chrisgurney/obsidian-note-toolbar#155]
**Description of the bug**
Cyrillic symbols are encoded after "copy as markdown" and "export" features. It should be decoded before use.
Examples of panel after "copy as markdown":
```markdown
> [!note-toolbar|sticky-center-button-wide-border] Note Панель
> - [:LiCopyPlus: %D0%94%D0%BE%D0%B4%D0%B0%D1%82%D0%B8]()<data data-ntb-menu="c295b5c2-f14a-435e-b57b-5cb250d61d8d"/>
> - [:LiTags: %D0%92%D0%BB%D0%B0%D1%81%D1%82%D0%B8%D0%B2%D0%BE%D1%81%D1%82%D1%96]()<data data-ntb-menu="d4a7c051-e25e-4478-87ad-0899da1fbe8c"/>
```

As can be seen, the header of the callout has Cyrillic symbols in the name, but not in elements name. After decoding worked fine.

**Steps to reproduce**
1. "Copy as markdown" or "Export" any panel with Cyrillic name of elements.

**Expected behavior**
No additional transformations required for any actions.

**Screenshots (if you think it will help)**
![image](https://github.com/user-attachments/assets/405fc357-0f09-4cdf-8c25-89197a04ac50)

**Desktop environment:**
 - OS: Windows 11
 - Obsidian version: 1.6.7
 - Note Toolbar version: 1.14-beta-19

**Comment by chrisgurney** [comment]
Thanks @laktiv ! Can you give me a string here that you're seeing the problem with, that I can copy/paste in, to test with?

**Comment by chrisgurney** [comment]
@laktiv found the issue; was being greedy with encoding. I just need to think through reversing the logic I had now.

**Comment by laktiv** [comment]
> Can you give me a string here that you're seeing the problem with, that I can copy/paste in, to test with?

What I need to provide? The code in the description of a bug could be used. In original panel it looks like this
"Додатки", "Властивості".
These are elements, not group pr menu's (the same issue as well).
![image](https://github.com/user-attachments/assets/fa583ecd-c08e-4d2a-9926-c32fd4079dcb)

**Comment by chrisgurney** [comment]
@laktiv OK try again with the latest beta.

**Comment by laktiv** [comment]
@chrisgurney WOW that was fast.
Thank you, tested all features. Works perfect! Case closed

**Comment by chrisgurney** [comment]
But I may have opened other issues in the process. 😅
