### ISSUE TITLE
"Copy URL" button can't be seen in Share window

### ISSUE THREAD

**Issue by laktiv** [chrisgurney/obsidian-note-toolbar#156]
**Description of the bug**
The "Copy URL" button is too far right in "Share panel" modal window. 

**Steps to reproduce**
1. Share panel with Cyrillic item. (long URL)

**Expected behavior**
Additional button "Copy URL"?

**Screenshots (if you think it will help)**
![image](https://github.com/user-attachments/assets/605f2b7f-b41d-4589-b31f-7e34324d60b4)

**Plugin, Theme links, and CSS snippets (if applicable):**
No theme. Own GUI snippet but it didn't touch any of buttons locations. Same issue when everything is turned off.

**Desktop environment:**
 - OS: Windown 11
 - Obsidian version: 1.6.7
 - Note Toolbar version: 1.14-beta-19

**Comment by chrisgurney** [comment]
@laktiv Interesting, I have CSS in place to prevent that from wrapping. Does this happen in a sandbox vault?

![CleanShot 2024-10-12 at 07 19 50@2x](https://github.com/user-attachments/assets/91e971c6-c76e-4d32-95cb-285f0faf3f75)

**Comment by chrisgurney** [comment]
Does your snippet touch any settings items by chance?

**Comment by chrisgurney** [comment]
@laktiv I've pushed another change, to force the styles around the URL. Can you please try again?

If that doesn't work, can you please try in a sandbox vault?

**Comment by laktiv** [comment]
> @laktiv I've pushed another change, to force the styles around the URL. Can you please try again?
> If that doesn't work, can you please try in a sandbox vault?

nope, but I'm trying to learn scss, it could be somewhere I guess. This why I tested with all snippets turned off before publishing (don't use themes, but was installed some before.

I've already using latest update and see changes. Looks fine, but I want to test, also with a untouched with tweaks vault. Will feedback in 10 minutes after testing.

![image](https://github.com/user-attachments/assets/963f8f8f-117a-449b-b94f-69248c84e682)

**Comment by chrisgurney** [comment]
I also wonder if your testing earlier was with an older version, perhaps because of the translations you were doing. (Your last screenshot was missing the toggle below the Copy button.)

**Comment by laktiv** [comment]
Thank you, works fine. The issue could be closed. Starting translation of new strings :)

> I also wonder if your testing earlier was with an older version
When "Copy as markdown" feature was available (first beta) all my elements were in English, so I didn't noticed the issue. When "Import/export" feature was available (also in 1st beta when appearance) I've already updated my toolbar with native names and saw this (as well as encoding) from the start. One more time sorry for late feedback.
