### ISSUE TITLE
Import from callout device view pref reset

### ISSUE THREAD

**Issue by laktiv** [chrisgurney/obsidian-note-toolbar#163]
**Description of the bug**
When I import 1-by-1 buttons from Examples page with editing view settings, if you touch view settings, it will reset applied view settings for previously imported buttons.

**Steps to reproduce**
1. Edit panel
2. Import from callout
3. Import button `> - [:LiDiscord:](https://discord.gg/obsidianmd) <!-- Obsidian Discord -->`
4. Adjust view settings for this button (for example - hide all on Desktop)
![image](https://github.com/user-attachments/assets/a435f807-b16d-4c84-84b0-56ba97aefed7)
5. Close settings menu
6. Same as 1-3 (next example button `> - [:LiMessageCircle:](https://forum.obsidian.md/) <!-- Obsidian forum -->`)
7. Adjust view settings for this button --> Will reset view button from p.4 and you will see it on the panel

**Desktop environment:**
 - OS: Windows 11
 - Obsidian version: 1.7.4
 - Note Toolbar version: 1.14.4

**Comment by chrisgurney** [comment]
@laktiv Nice find. I can reproduce. Will dig in on this. Thanks!

**Comment by chrisgurney** [comment]
Fix is in [1.14.5](https://github.com/chrisgurney/obsidian-note-toolbar/releases/tag/1.14.5).
