### ISSUE TITLE
Toolbar diappears when switching between views

### ISSUE THREAD

**Issue by anareaty** [chrisgurney/obsidian-note-toolbar#164]
**Description of the bug**

Since the 1.14 version toolbar that placed below properties diappears when switching between views. It only returns after switching back or reloading the page. Also sometimes after switching back it is shown on the top instead of below properties.

**Steps to reproduce**

1. Add toolbar to the note.
2. Set toolbar position to "below properties".
3. Try to switch note view from source to preview view or from preview to source view.

**Expected behavior**

Toolbar should stay visible in both views. 

**Debug info:**
SYSTEM INFO:
	Obsidian version: v1.7.4
	Installer version: v1.6.7
	Operating system: #47-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 21:40:26 UTC 2024 6.8.0-47-generic
	Login status: not logged in
	Language: ru
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Note Toolbar v1.14.5

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Desktop environment:**
 - OS: Ubuntu and Windows 10
 - Obsidian version: 1.7.4
 - Note Toolbar version: 1.14.5

**Comment by chrisgurney** [comment]
@anareaty I think I have this fixed in the latest release (1.14.7). Can you give it a try please, and let me know how it goes? Thanks!

**Comment by anareaty** [comment]
It seems to be working properly now, thank you!
