### ISSUE TITLE
Some commands exist but appear unavailable

### ISSUE THREAD

**Issue by likemuuxi** [chrisgurney/obsidian-note-toolbar#170]
**Description of the bug**

some commands exist but appear not exit

**Screenshots (if you think it will help)**
_Video or a GIF would be appreciated._

![image](https://github.com/user-attachments/assets/a17d2e6a-e649-4d40-a0ad-fd2bf2f581a6)
![image](https://github.com/user-attachments/assets/9f880111-de32-4a8c-ac93-a487b7ea5ec2)

**Desktop environment:**
 - OS: Windows
 - Obsidian version: 1.7.4
 - Note Toolbar version: 1.14.9

**Comment by chrisgurney** [comment]
@likemuuxi Thanks for the bug report! Can you please provide some examples of the plugins that these commands are from?

**Comment by chrisgurney** [comment]
@Moyf if you have a moment, are you able to replicate this bug?

At least on macOS I changed my language, and entered 引用 and am able to select the command no problem.

**Comment by likemuuxi** [comment]
> @likemuuxi Thanks for the bug report!
> 
> 1. 你能提供更多关于如何添加此项目的详细步骤吗？
> 2. 这是“切换块引用”命令还是其他命令？
> 3. 你使用黑曜石语的具体语言是什么？

1. Here are my adding steps
![1729601340455-1729599406066-20241022_201257](https://github.com/user-attachments/assets/dc516d1d-7cf6-4ef0-ab5d-0088d921823d)
2. This command is called `Toggle blockquote` in English
3. My language is Chinese

**Comment by Moyf** [comment]
> @Moyf if you have a moment, are you able to replicate this bug?
> 
> At least on macOS I changed my language, and entered 引用 and am able to select the command no problem.
> 
> ![CleanShot 2024-10-22 at 06 53 45@2x](https://private-user-images.githubusercontent.com/17337703/378807585-dbb24313-5f83-4b10-bda6-671c814c8739.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MDg4MjQsIm5iZiI6MTcyOTYwODUyNCwicGF0aCI6Ii8xNzMzNzcwMy8zNzg4MDc1ODUtZGJiMjQzMTMtNWY4My00YjEwLWJkYTYtNjcxYzgxNGM4NzM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDE0NDg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhYzNlN2QzZjJhNWQzZTBiZTI4Njk3ODhmOTA0MTM0YWYyNThjZDZiMDhmOTlhNmZmNGE2OGRhMjMyOWZlNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Dr__6BjSCYyW1g1DuoQ7KqUZEeCLvttK3K3JwLaLqmA)

![image](https://github.com/user-attachments/assets/27a14abf-783e-4341-ba89-0496753fb8dc)

Oh.. On my PC (Windows) with Chinese language, I can replicate this issue 🤔

The "引用" means "Toggle Quote" AKA this command:
![3e86bea1-4fd1-42c2-bace-ada88dd3507f](https://github.com/user-attachments/assets/d965a3e5-3f71-44c7-a865-744afed64f6a)

I tried the English command, it works:
![image](https://github.com/user-attachments/assets/5e4e1445-d88a-4d57-9435-54cfa5f16d9b)

So strange.. I guess it could be due to OB's localization?

**Comment by chrisgurney** [comment]
@likemuuxi Thank you for the video! It was super helpful to see what you were typing. Once I was able to turn on Chinese input I was able to reproduce as well. @Moyf Thank you for confirming as well!

![CleanShot 2024-10-22 at 10 55 29](https://github.com/user-attachments/assets/19a4e6e4-3b34-47db-834e-d7c25ab4d9b0)

I will investigate when I get a chance.

**Comment by Moyf** [comment]
> @likemuuxi Thank you for the video! It was super helpful to see what you were typing. Once I was able to turn on Chinese input I was able to reproduce as well. @Moyf Thank you for confirming, and for the explanation as well!
> 
> ![CleanShot 2024-10-22 at 10 55 29](https://private-user-images.githubusercontent.com/17337703/378895708-19a4e6e4-3b34-47db-834e-d7c25ab4d9b0.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MDk2MjgsIm5iZiI6MTcyOTYwOTMyOCwicGF0aCI6Ii8xNzMzNzcwMy8zNzg4OTU3MDgtMTlhNGU2ZTQtM2IzNC00N2RiLTgzNGUtZDdjMjVhYjRkOWIwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDE1MDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ZDkwMjNjZWQ1ZDhjYjNhZjNiYjZkZDI3MTg4OTEwNmZmMDUzOThkNjNhNTY2YzQ4YWI3YWExOWRkNmRkN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LYqncM_aGPum3H7-waEP9XgDLIrv-MbJZs_ViBLhLLI) [ ![CleanShot 2024-10-22 at 10 55 29](https://private-user-images.githubusercontent.com/17337703/378895708-19a4e6e4-3b34-47db-834e-d7c25ab4d9b0.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MDk2MjgsIm5iZiI6MTcyOTYwOTMyOCwicGF0aCI6Ii8xNzMzNzcwMy8zNzg4OTU3MDgtMTlhNGU2ZTQtM2IzNC00N2RiLTgzNGUtZDdjMjVhYjRkOWIwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDE1MDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ZDkwMjNjZWQ1ZDhjYjNhZjNiYjZkZDI3MTg4OTEwNmZmMDUzOThkNjNhNTY2YzQ4YWI3YWExOWRkNmRkN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LYqncM_aGPum3H7-waEP9XgDLIrv-MbJZs_ViBLhLLI) ](https://private-user-images.githubusercontent.com/17337703/378895708-19a4e6e4-3b34-47db-834e-d7c25ab4d9b0.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MDk2MjgsIm5iZiI6MTcyOTYwOTMyOCwicGF0aCI6Ii8xNzMzNzcwMy8zNzg4OTU3MDgtMTlhNGU2ZTQtM2IzNC00N2RiLTgzNGUtZDdjMjVhYjRkOWIwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDE1MDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ZDkwMjNjZWQ1ZDhjYjNhZjNiYjZkZDI3MTg4OTEwNmZmMDUzOThkNjNhNTY2YzQ4YWI3YWExOWRkNmRkN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LYqncM_aGPum3H7-waEP9XgDLIrv-MbJZs_ViBLhLLI) [ ](https://private-user-images.githubusercontent.com/17337703/378895708-19a4e6e4-3b34-47db-834e-d7c25ab4d9b0.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MDk2MjgsIm5iZiI6MTcyOTYwOTMyOCwicGF0aCI6Ii8xNzMzNzcwMy8zNzg4OTU3MDgtMTlhNGU2ZTQtM2IzNC00N2RiLTgzNGUtZDdjMjVhYjRkOWIwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDE1MDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ZDkwMjNjZWQ1ZDhjYjNhZjNiYjZkZDI3MTg4OTEwNmZmMDUzOThkNjNhNTY2YzQ4YWI3YWExOWRkNmRkN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LYqncM_aGPum3H7-waEP9XgDLIrv-MbJZs_ViBLhLLI)
> 
> I will investigate when I get a chance.

You even specifically switched to Chinese input, so enthusiastic!
(But just a quick note, you should have typed `yin'yong`: 引用

**Comment by chrisgurney** [comment]
@Moyf Haha, thanks. Tried it again with `yin'yong` and got the same result, fortunately for me. 👍

**Comment by chrisgurney** [comment]
@Moyf Actually, I wasn't looking close enough at the characters. 🤦‍♂️

This actually _does_ work for me:

![CleanShot 2024-10-23 at 08 11 28](https://github.com/user-attachments/assets/1b65b08d-c468-435c-aa05-e359b5f20e68)

**Comment by Moyf** [comment]
> I thought it had to do with the `onchange()` being triggered and saved (as Pinyin) before the Chinese characters were replaced. But I put in some debug statements and it looks like it is saving it correctly, _with_ the Chinese characters. (Again, on macOS.)
> 
> Now I'm stumped again, and hoping it's not a Windows-only bug.
> 
> @Moyf Can you record what you did?

I did some tests:

[1] Other Chinese Command:
![4ec86b0b-f3dc-4346-a1e7-f97443a0fbda](https://github.com/user-attachments/assets/8a269f9c-170b-42fa-8a26-7084e6a04617)

I tried "保存当前文件" (Save Current File), and delete one character, the warning appears.
After I choose the item in auto-suggestion, the warning stays for a while and disappears. 
(It was refreshed in some way?)


[2] I tried to just **Paste** the word "引用" - it should have nothing related to IME (PinYin) - and still warns.
![2e1cf8f5-e914-46fc-8fbf-df95524e5849](https://github.com/user-attachments/assets/6b93538d-84ae-4ff0-8cb9-a6d3c6346dda)


[3] I use `app.commands to see the command itself:
![image](https://github.com/user-attachments/assets/84568892-9748-409e-88f5-20f67397f881)

Its name is "引用"- precisely same word!!
So I'm also confused now.. I'll try it on my mac later.

**Comment by Moyf** [comment]
Just tested in my macOS (Sequoia 15.1) / Obsidian 1.7.4, it's same with the gif in [2]

So strange.. I'm afraid it might be some issues inside the Obsidian.

I also checked the Localization file in [this page](https://github.com/obsidianmd/obsidian-translations/blob/master/zh.json), line 568, it seems everything is OK.

Which is even stranger is that, as you can see, I tried another command "Shell commands: Execute: 引用记号附链接" - this should be more complex but it works 😂
![image](https://github.com/user-attachments/assets/bd922c33-afb6-4949-8780-7533956a8fbb)


---

So for @likemuuxi I got 2 suggestions based on this weird situation:

1. Switching to English language in Obsidian 😏
2. Use plugin like **Commander** to warp the origin "引用" command as a new command, and bind this new command

![image](https://github.com/user-attachments/assets/13b0821f-1a96-4643-8d04-25bd247d3817)

**Comment by chrisgurney** [comment]
@Moyf Here's the CommandSuggester, which displays the command options:

https://github.com/chrisgurney/obsidian-note-toolbar/blob/master/src/Settings/UI/Suggesters/CommandSuggester.ts

The code that highlights the field if there's a problem is here:

https://github.com/chrisgurney/obsidian-note-toolbar/blob/master/src/Settings/UI/Modals/ToolbarSettingsModal.ts#L1211

First thought: I _think_ I should be using this when lower-casing strings, and I'm not: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLocaleLowerCase

Thank you for taking a look!

**Comment by likemuuxi** [comment]
> 刚刚在我的macOS（Sequoia 15.1）/Obsidian 1.7.4中进行了测试，它与[2]中的gif相同
> 
> 真奇怪。。恐怕黑曜石内部有些问题。
> 
> 我还检查了本页第568行的本地化文件，似乎一切正常。
> 
> 更奇怪的是，正如你所看到的，我尝试了另一个命令“Shell commands:Execute：引用编号附件”-这应该更复杂，但它有效😂 ![image](https://private-user-images.githubusercontent.com/4013062/379352318-bd922c33-afb6-4949-8780-7533956a8fbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MzI0NjgsIm5iZiI6MTcyOTczMjE2OCwicGF0aCI6Ii80MDEzMDYyLzM3OTM1MjMxOC1iZDkyMmMzMy1hZmI2LTQ5NDktODc4MC03NTMzOTU2YThmYmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjRUMDEwOTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzcxOTVkYmI2M2Q0NzZhZTQwZWRmYzc2MTRmZjg1M2E4YmUyNWNjNzg5NTFmY2E2OWU5MzRhOTRkZTEwMTZiOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.EsjndR2LRtgKCxfqC83zaDmQxc163jsga8n-vkCmd10)
> 
> 因此，对于@likemuuxi，基于这种奇怪的情况，我有两个建议：
> 
> 1. 在黑曜石语中切换到英语😏
> 2. 使用类似Commander的插件将原始“引用”命令扭曲为新命令，并绑定此新命令
> 
> ![image](https://private-user-images.githubusercontent.com/4013062/379353126-13b0821f-1a96-4643-8d04-25bd247d3817.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MzI0NjgsIm5iZiI6MTcyOTczMjE2OCwicGF0aCI6Ii80MDEzMDYyLzM3OTM1MzEyNi0xM2IwODIxZi0xYTk2LTQ2NDMtOGQwNC0yNWJkMjQ3ZDM4MTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjRUMDEwOTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2U0YmUwYWI3M2MzNDVlZWI3NTZmZDNmMTE1MDcwYzlhM2RmMWViZmU4NTUzYmUwYTRmMDgyMTYzZjRhMWYwZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.f3X4NDmxrOz83ubPiuTBuH8yTLwZa6TAvhlqiCnFvCk)

@Moyf Thanks for the suggestion, but in my tests this problem occurred not only with `引用`/`Toggle blockquote` to this command, but also with other commands like `代码块`/`Toggle code`. @chrisgurney One thing worth noting is that the information I imported from the [share command](https://chrisgurney.github.io/obsidian-note-toolbar/open.htm?uri=obsidian%3A%2F%2Fnote-toolbar%3Fimport%3D%3E%20%5B!note-toolbar%5D%20Insert...%0A%3E%20-%20%5B%3ALiPaperclip%3A%5D()%3Cdata%20data-ntb-command%3D%22editor%3Aattach-file%22%2F%3E%20%3C!--%20Insert%20attachment%20--%3E%0A%3E%20-%20%5B%3ALiAlertTriangle%3A%5D()%3Cdata%20data-ntb-command%3D%22editor%3Ainsert-callout%22%2F%3E%20%3C!--%20Insert%20callout%20--%3E%0A%3E%20-%20%5B%3ALiSquareCode%3A%5D()%3Cdata%20data-ntb-command%3D%22editor%3Ainsert-codeblock%22%2F%3E%20%3C!--%20Insert%20code%20block%20--%3E%0A%3E%20-%20%5B%3ALiLineHorizontal%3A%5D()%3Cdata%20data-ntb-command%3D%22editor%3Ainsert-horizontal-rule%22%2F%3E%20%3C!--%20Insert%20horizontal%20rule%20--%3E%0A%3E%20-%20%5B%3ALiFunctionSquare%3A%5D()%3Cdata%20data-ntb-command%3D%22editor%3Ainsert-mathblock%22%2F%3E%20%3C!--%20Insert%20math%20block%20--%3E%0A%3E%20-%20%5B%3ALiTable2%3A%5D()%3Cdata%20data-ntb-command%3D%22editor%3Ainsert-table%22%2F%3E%20%3C!--%20Insert%20table%20--%3E%0A) was available, and only showed this when I added it myself.

**Comment by likemuuxi** [comment]
![20241104_211554](  https://github.com/user-attachments/assets/7785d53b-fe16-4498-b60b-5cca926285e2  )

In the beta version, the same issue still persists

**Comment by chrisgurney** [comment]
@likemuuxi OK thanks for checking.

**Comment by likemuuxi** [comment]
I don't know why, but only the `editor: toggle blockquote` and `editor: insert code block` commands were selected and not added to the `commandId` key in `data.json`. However, `console. log' ("Available commands:"), Object.keys((this.app as any).commands.commands));` The command does exist, I think we can add debugging information to confirm what exactly happened.

**Comment by chrisgurney** [comment]
@likemuuxi @Moyf OK I have a fix in the latest beta.

I'm not sure what the cause was in the end, but I changed how the command ID is updated from the CommandSuggester field, which I _think_ I was doing incorrectly and was being overridden by Obsidian somehow. I was able to duplicate the issue with the _Toggle code block_ command.

Please let me know if this works for you @likemuuxi!

**Comment by likemuuxi** [comment]
That's great! There is no such problem now.🎉
