### ISSUE TITLE
Import from Settings doesn't transfer mobile styles

### ISSUE THREAD

**Issue by laktiv** [chrisgurney/obsidian-note-toolbar#189]
**Description of the bug**
Import and export of panel doesn't transfer the setup style of panel.
Applied for issues:
- from text callout -> import panel in menu
- copy as markdown text -> menu
- export as obsidian:// link

**Desktop environment:**
 - OS: windows 11, ios 18
 - Obsidian version: 1.7.7
 - Note Toolbar version: beta17

**Comment by chrisgurney** [comment]
Thanks for logging this @laktiv !

I'm not sure I fully understand the steps you followed here. Can you provide a video perhaps?

**Comment by laktiv** [comment]
Hi @chrisgurney.
First of all - please take my apology for very long replies latest time. Finding a new job plus constant electricity off leaves not many time for extra activities.

I've recorded one issue - create new toolbar from callout text. Please check it.
![note-toolbar](https://github.com/user-attachments/assets/40ab64f8-db66-46ad-9dee-c1ca670c14c6)

It should looks like this:
![image](https://github.com/user-attachments/assets/260b7d38-e555-4807-8474-ccf121873b18)

I've tried this in all described scenarios in the first message - the result is the same. Kindly ask to check not only mobile's styles, but desktop's as well. Because I'm sure that it was the case for both types of styles. This one I should get from archive to record and didn't change the PC's.

If I still have leave some questions - please feedback me back. Thank you

**Comment by chrisgurney** [comment]
@laktiv Thank you. I understand the problem now, and yes that's indeed a bug.

Good luck to you.

**Comment by chrisgurney** [comment]
Fixed in [`1.16-beta-07`](https://github.com/chrisgurney/obsidian-note-toolbar/releases/tag/1.16-beta-07). Thanks @laktiv!
