### ISSUE TITLE
Next daily note in Android reopen Obsidian

### ISSUE THREAD

**Issue by javiavid** [chrisgurney/obsidian-note-toolbar#19]
**Description of the bug**
When I use the command "Daily notes: Open next daily note", obsidian restarts and the same note appears as it had.
On Windows it works fine.

**Steps to reproduce**
Create a button
Add the Daily notes command: Open next daily note
Click on the created button

**Expected behavior**
Open the next daily note

**Screenshots (if you think it will help)**

**Plugin links (if applicable to the issue):**

**Desktop environment:**
 - OS: windows 11
 - Obsidian version: 1.5.12
 - Note Toolbar version: 1.4.7

**Mobile environment (if applicable to the issue):**
 - Device: Samsung S10+
 - OS: Android 12
 - Obsidian version: 1.5.12 (134)
 - Note Toolbar version: 1.4.7

**Additional context**
_Add any other context about the problem here._

**Comment by chrisgurney** [comment]
@javiavid Thank you for the bug report!

Can you confirm if that same command does anything from if you run it outside of the toolbar, in the same note?

**Comment by javiavid** [comment]
Yes, there are more notes before and after. I have tested the command from the command palette and it works correctly on Android.

Thanks for the plugin, it is very useful.

**Comment by FelipeRearden** [comment]
Trying to help here...

What if you use a URI instead of Command? Maybe could work 🙏

**Comment by chrisgurney** [comment]
@javiavid Hmm. Can you show me your configuration? Take a screenshot of the settings?

**Comment by javiavid** [comment]
I just tried it again and it works fine now, maybe it was a synchronization problem with obsidian sync ¿?
I had previously tried closing Obsidian and opening it again, but it didn't work well.

Sorry for the inconvenience

**Comment by chrisgurney** [comment]
@javiavid I've created a ticket (#21) you can monitor for updates on this issue, if you wish.

**Comment by javiavid** [comment]
Hello, I have already found the error, it occurs when you are in Reading mode on Android, if it is in live view there is no problem.

**Comment by javiavid** [comment]
Hello, I have already found the error, it occurs when you are in Reading mode on Android, if it is in live view there is no problem.

**Comment by chrisgurney** [comment]
@javiavid What I believe to be the underlying issue should be fixed now, with the latest release in Community Plugins. Let me know if it's happened again since your last message, and if not, we'll close this issue. Thanks!

**Comment by javiavid** [comment]
Hi, I have tested the latest beta version 1.5.13 and the community 1.5.15. The error keeps happening...

**Comment by chrisgurney** [comment]
Others experiencing this (or a similar?) issue:

- https://www.reddit.com/r/ObsidianMD/comments/1c7yzs5/comment/l0dyugr/
- https://www.reddit.com/r/ObsidianMD/comments/1c7yzs5/comment/l0jfu6j/

**Comment by chrisgurney** [comment]
OK (thankfully?) this issue's been reported recently:
https://forum.obsidian.md/t/openlinktext-run-outside-of-a-markdown-editor-crashes-obsidian-mobile-on-android/79561

There's a [possible workaround](https://forum.obsidian.md/t/openlinktext-run-outside-of-a-markdown-editor-crashes-obsidian-mobile-on-android/79561/2) to try involving changing anchors to spans, but this _could_ cause accessibility issues.

I may end up implementing the workaround temporarily, until this is fixed in core Obsidian.

**Comment by chrisgurney** [comment]
Version `1.6.0-beta` is now available (via BRAT) that should hopefully have a fix for this issue. Would appreciate help with testing to get confirmation that this issue is fixed in both Editing and Reading mode.

**Comment by javiavid** [comment]
Solved! thank you

**Comment by chrisgurney** [comment]
And @FelipeRearden I had to change `a` to `span` tags within the toolbar, which required some updates to the keyboard accessibility (the `Focus` command). Would appreciate your help with testing `1.6.0-beta` (via BRAT) if you're able!

**Comment by chrisgurney** [comment]
@FelipeRearden Thsnk you so much! Good to hear!

**Comment by chrisgurney** [comment]
Reports coming in from Reddit are that it's fixed for those Android users as well.

- https://www.reddit.com/r/ObsidianMD/comments/1c7yzs5/comment/l0yzssc/
- https://www.reddit.com/r/ObsidianMD/comments/1bzwk24/comment/l0wi637/

**Comment by chrisgurney** [comment]
This fix is now released to Community Plugins in `v1.6.2`.
