### ISSUE TITLE
[BUG] Share not working in 1.15-Beta-17

### ISSUE THREAD

**Issue by Moyf** [chrisgurney/obsidian-note-toolbar#190]
**Description of the bug**

![image](https://github.com/user-attachments/assets/45259645-7f75-465b-b5b4-08cc33176dc9)

When pressing **Share** or **Copy as Callout**, the console shows:
![image](https://github.com/user-attachments/assets/b913368e-c9d2-4dd2-825a-134b54c0de61)

![image](https://github.com/user-attachments/assets/a081651f-00c0-461c-969a-0531c4dd1ef5)

**Steps to reproduce**

1. Right click and choose **Share**

Also reproduced on my sandbox vault:
![image](https://github.com/user-attachments/assets/291425e3-d3ad-4184-84d7-d56c195e1d2f)

**Expected behavior**

**Debug info:**
SYSTEM INFO:
	Obsidian version: v1.7.7
	Installer version: v1.7.7
	Operating system: Windows 11 Pro 10.0.22635
	Login status: logged in
	Language: en
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: dark
	Community theme: Aura v2.3.3
	Snippets enabled: 23
	Restricted mode: off
	Plugins installed: 106
	Plugins enabled: 70
		26: Note Toolbar v1.15-beta-17

**Desktop environment:**
 - OS: Windows11
 - Obsidian version: 1.7.7
 - Note Toolbar version: 1.15-beta-17

**Comment by chrisgurney** [comment]
Thanks @Moyf ! Fix should be in the next version.

**Comment by chrisgurney** [comment]
Fixed in [1.15-beta-18](https://github.com/chrisgurney/obsidian-note-toolbar/releases/tag/1.15-beta-18).

**Comment by Moyf** [comment]
> Fixed in [1.15-beta-18](https://github.com/chrisgurney/obsidian-note-toolbar/releases/tag/1.15-beta-18).

Great! Thank you, Chris 🍻
