### ISSUE TITLE
Creating a toolbar from callout when it absent. 

### ISSUE THREAD

**Issue by laktiv** [chrisgurney/obsidian-note-toolbar#194]
**Description of the bug**
Saw it a few days ago, don't have enough time, but I understand that to repeat it could take some time. So please just take a note of it before record to develop backlog. I'll try to describe as detailed as possible.

1. There is assigned in settings metadata column in the note `property name = notetoolbar`
2. As value there was unavailable panel name `notetoolbar: _ edit` (it could be just "edit" I don't remember, but I named my panel with extra symbols in front to sort the by types)
3. An error about this was popping up like every few seconds
4. To close them, was start to click on toolbar for a couple time, but where there were a lot of them
5. Then I've found out that I had a bunch of empty panels named `"e"` in the settings

PS: Sorry, didn't remember what was the text in callout. My bad.

**Expected behavior**
1. Not so often pop-up's of error
2. Don't create black toolbar on clicking

**Desktop environment:**
 - OS: Windows 11
 - Obsidian version: 1.7.6
 - Note Toolbar version: 1.15-beta-17

**Comment by chrisgurney** [comment]
Thanks for the note @laktiv .

Only one popup should appear when you update a property to mention a toolbar that doesn't exist.

How did you set the `notetoolbar` property name to the toolbar name? Was this done manually by you, or by a plugin or a script, perhaps?

**Comment by chrisgurney** [comment]
Note to self: Do I need to debounce the code within the metadata cache listener?

https://discord.com/channels/686053708261228577/840286264964022302/996558806844702750

**Comment by laktiv** [comment]
> How did you set the `notetoolbar` property?

In general, I have assigned one toolbar by folder mapping '*'. This particular case was on an old note where the property was in there before. As I mentioned, had no time to repeat and dig down, sorry.
But the plugin could make some bad things. Because there are no easy way in Obsidian just to have manipulate the property besides keyboard typing, and I was playing with scripts before and I'm not a programmer. I wanted to +/- just one value and don't touch the other in the field in cssclasses.. No success. But why I posted it - the way NY behave was very weird. And I didn't touch my 'notetoolbar' property. The ability to have specialized toolbars where you need is very cool.

**Comment by chrisgurney** [comment]
@laktiv I've temporarily disabled this notice in `1.15.2` while I dig into this problem, so it's not annoying you or others. This might take me a few days to get to. Thanks again for pointing it out.

**Comment by imed-ghomari** [comment]
I encountered the same issue with that version of the plugin. I had to revert to the previous version to disable the pop-ups. I'm not sure how the notetoolbar was activated; I was just typing normally in the note when the notifications started appearing unexpectedly. I hadn’t triggered any commands or interacted with any toolbar elements. Therefore, I’m unsure what might be causing this problem in that version of the plugin.

**Comment by chrisgurney** [comment]
I've pushed a fix for what I _thought_ was the original issue, in [1.5.3](https://github.com/chrisgurney/obsidian-note-toolbar/releases/tag/1.15.3).

If that doesn't fix what you experienced, can you provide a video, whenever you're able? Thanks!

**Comment by laktiv** [comment]
> If that doesn't fix what you experienced, can you provide a video, whenever you're able? Thanks!
Ok. I will try to do various things to check the issue, along with other notes I've took before. Will right to task list, but with no time set. fyi

**Comment by chrisgurney** [comment]
Closing for now, unless you're able to reproduce the problem again @laktiv.
