### ISSUE TITLE
Command for previous/next daily note not working

### ISSUE THREAD

**Issue by machado-t** [chrisgurney/obsidian-note-toolbar#24]
Commands for previous/next daily note are not working.
Curiously, these commands are not found in my command palette. 
A different command from the Daily Notes plugin (today's note) is working.
I'm on Windows. Obsidian is up to date.

**Comment by chrisgurney** [comment]
Some commands don't appear in all cases, I'm not sure why. Though I _think_ in the case of the previous/next command, you need to be in a note that has title with the `Date format` as specified in the settings.

For example, if I'm in a note that has a name like "Untitled" the only command I see is `Daily notes: Open today's daily note`. Once I'm in one with a name like "2024-04-08" (per the default), the `Daily note: Open next/previous daily note` commands becomes available.

What note are you attempting to execute the command from?

**Comment by machado-t** [comment]
Yes, thank you. Considering I cannot find the command in the command palette, I don't think this is an issue relating to this plugin. Thanks

**Comment by chrisgurney** [comment]
@machado-t I'm seeing other reports of this issue, and there's one here where the commands are actually working for this user:
https://www.reddit.com/r/ObsidianMD/comments/1bzwk24/comment/kytheb8/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

Reopening as I investigate further.

**Comment by chrisgurney** [comment]
I don't believe this is related to the Android reported issue. It just so happened both were initially reported around Daily Notes. Closing for now.
