### ISSUE TITLE
Toolbar not rendering reliably (folder mode)

### ISSUE THREAD

**Issue by mitchmeister** [chrisgurney/obsidian-note-toolbar#35]
**Description of the bug**
When swapping back to the open tab of a note with a folder toolbar it doesn't reliably rerender the toolbar.

**Steps to reproduce**
3 tabs open, each using a toolbar.  Swap between tabs.  In the video below the toolbars never render but sometimes they do.

**Screenshots (if you think it will help)**
https://github.com/chrisgurney/obsidian-note-toolbar/assets/6250875/a74ed554-6cc0-441c-9f6c-e4ad5adc5b50

**Desktop environment:**
 - OS: Macos 14.4.1
 - Obsidian version: 
 - Note Toolbar version: 1.4.12

Mobile (iOS) doesn't seem to have this issue

**Comment by chrisgurney** [comment]
I'm working on changes to rendering in the next version, so would love if you could try out the beta when it's ready.

**Comment by mitchmeister** [comment]
👍🏻

**Comment by chrisgurney** [comment]
@mitchmeister The beta is now available (via BRAT): https://github.com/chrisgurney/obsidian-note-toolbar/discussions/40

**Comment by mitchmeister** [comment]
Nice work Chris.  Seems to render reliably now.  Well in the first 5 minutes of testing anyway.  I'll raise issues if anything unexpected found.

Mitch

**Comment by chrisgurney** [comment]
@mitchmeister Great to hear. Let me know how testing goes!

**Comment by chrisgurney** [comment]
@mitchmeister The latest version is now available on Community Plugins with this change. Please let me know if it helps! 🤞
