### ISSUE TITLE
Bar not showing on mobile

### ISSUE THREAD

**Issue by tivervac** [chrisgurney/obsidian-note-toolbar#39]
**Description of the bug**
I just installed the plugin on iOS and can’t get the bar to render simply through folder mapping. I got it to work with properties, but I don’t feel like adding a property to _all_ my files.

**Expected behavior**

The bar renders on all files (or at least root files) with simply my folder mapping.

**Screenshots (if you think it will help)**
_Video or a GIF would be appreciated._

![IMG_5979](https://github.com/chrisgurney/obsidian-note-toolbar/assets/3389524/243fa1bc-cc47-4eea-b6d4-e5fdfe39c3b9)
![IMG_5980](https://github.com/chrisgurney/obsidian-note-toolbar/assets/3389524/241bae0a-99c1-44b1-8719-310f005df8b9)
![IMG_5981](https://github.com/chrisgurney/obsidian-note-toolbar/assets/3389524/80d78ae8-9025-4562-b87c-45ccbc907cd6)

**Theme links and CSS snippets (if applicable):**
_Themes and CSS snippets can affect the display of the toolbar. Include any being used here to help diagnose display issues._

**Plugin links (if applicable):**
_If you're using a specific plugin that isn't working with the toolbar, link it here._

**Mobile environment (if applicable to the issue):**
 - Device: iPhone 11 Pro
 - OS: iOS 17.4.1
 - Obsidian version: 1.5.12
 - Note Toolbar version: 1.4.12

**Additional context**
_Add any other context about the problem here._

**Comment by chrisgurney** [comment]
@tivervac Thanks for logging this issue!

The beta I've _just_ released adds support for a `*` mapping which lets you globally map toolbars (and another for `/` if you'd prefer to just map root notes). If you'd prefer not to install the beta (via BRAT), the Community Plugins version should be updated within the week or so, depending on how testing goes.

Read more here: https://github.com/chrisgurney/obsidian-note-toolbar/discussions/40
