### ISSUE TITLE
Clicking any Button Causes Obsidian to Reload

### ISSUE THREAD

**Issue by MrComputron** [chrisgurney/obsidian-note-toolbar#41]
https://github.com/chrisgurney/obsidian-note-toolbar/assets/46870771/9e5fd2fd-1e8a-45a7-a85a-49ff99da23e5

https://github.com/chrisgurney/obsidian-note-toolbar/assets/46870771/3eb99981-4e2c-4e8b-9505-261499a2769a

Selecting any button in a toolbar on mobile causes Obsidian to reload.

**Steps to reproduce**

1. Be in obsidian (either live preview or preview)
2. Click any note toolbar button

**Expected behavior**

- Expect the action to be performed without reloading the vault
- Sometimes performs the action, then quickly afterwards reloads the vault

**Screenshots (if you think it will help)**
_Video or a GIF would be appreciated._

**Theme links and CSS snippets (if applicable):**
Issue occurs with all themes, however installed themes are:
- Wikipedia
- Vicious
- Ultra Lobster
- Typomagical
- Serenity
- PLN
- Origami
- Obuntu
- ObsidianNotion
- Minimal
- Heboric
- Gummy
- Garden Gnome (Adwaita, GTK)
- Encore
- Dracula Official
- Border
- Bolt
- AnuPpuccin

**Plugin links (if applicable):**
_If you're using a specific plugin that isn't working with the toolbar, link it here._
Not sure if any of these is responsible
- Abbreviations expander
- Auto note mover
- Book search
- Buttons
- Checklist
- Commander
- Dataview
- Floating Search
- Footnote shortcut
- Force note view mode
- Heatmap calendar
- Ink
- List callouts
- map view
- meta bind
- natural language dates
- note refactor
- note toolbar
- obsidian columns
- omnivore
- paste url into selection
- periodic notes
- quick switcher ++
- Quickadd
- slash commander
- style settings
- tag wrangler
- tasks
- templater
- tracker
- typewriter scroll
- various complements

**Desktop environment:**
 - OS: Windows 10 Pro
 - Obsidian version: 
 - Note Toolbar version: 

**Mobile environment (if applicable to the issue):**
 - Device: 
 - OS: 
 - Obsidian version: 1.5.12
 - Note Toolbar version: 1.4.12

**Additional context**
Thanks.

**Comment by chrisgurney** [comment]
@MrComputron thanks for logging the issue!

Can you provide more details on what the links in your toolbar are that you're getting this result with? Are they Commands, Files, or URIs? What exactly are they?

**Comment by chrisgurney** [comment]
@MrComputron Thanks for the recordings. Can you give an example of one of the commands you're using that's exhibiting the issue?

**Comment by MrComputron** [comment]
All commands have at times had this issue. Commands I've set up in toolbars include:
- Bookmark file
- Bookmark block under cursor
- Bookmark heading under cursor
- Open settings
- Note composer extract heading
- Move current file to another folder
- Previous daily note
- Next daily note
- Daily note
- Book search create new book note
- Change theme
- (Ink plugin) New drawing / new writing
- Toggle live preview / source mode
- Toggle reading view

The major frustration with it is that it works and stops working inconsistently...sometimes it works for 5-6 button presses before it reloads, sometimes it reloads on the first, and there is no obvious pattern to when it will reload.

**Comment by chrisgurney** [comment]
Appreciate all the details so far. 

Is it possible to perhaps start a new vault with _just_ the Note Toolbar plugin and use a core plugin command, to see if it happens with that setup?

**Comment by chrisgurney** [comment]
@MrComputron If you're willing to try out the beta, I've just pushed an update that you can try (look for `v1.5.6-beta` or later). I'd be interested in whether this fixes the issue for you or not.

- Installation instructions (via BRAT) here: https://github.com/chrisgurney/obsidian-note-toolbar?tab=readme-ov-file#installation
- More about the beta here: https://github.com/chrisgurney/obsidian-note-toolbar/discussions/40

## Technical Notes

The change was moving the `preventDefault()` calls earlier in the click handler, which previously were _after_ attempting to execute the command. My theory (unproven) is that occasionally, with lots of plugins, that call might take a while to do, and without the `preventDefault()` being earlier was allowing the click (to `#`) to actually go through. (I've just read it's good practice to do the `preventDefault()` earlier, anyway.)

**Comment by chrisgurney** [comment]
@MrComputron The latest version is now available on Community Plugins with this change. Please let me know if it helps! 🤞

**Comment by MrComputron** [comment]
It is all working without issue now and I am very pleased about it. Thanks for the update and again for all the work you are putting into this plugin!
