### ISSUE TITLE
Toolbar on calendar plugin sidebar - Top Fixed

### ISSUE THREAD

**Issue by CCerrer** [chrisgurney/obsidian-note-toolbar#44]
**Description of the bug**
My daily note toolbar is appearing on the calendar plugin sidebar

**Steps to reproduce**

1. Install 1.5.13 beta
2. Put a toolbar on daily notes folder with Top Fixed option
3. use calendar a bit, open the notes with the sidebar and stuff.
4. In a couple of minutes the toolbar will appear on calendar sidebar

**Expected behavior**
Do not appear any toolbar on calendar sidebar

**Screenshots (if you think it will help)**
![image](https://github.com/chrisgurney/obsidian-note-toolbar/assets/88400130/7c3f3b7c-62a4-4f47-be7c-90aeb0af07c0)
![image](https://github.com/chrisgurney/obsidian-note-toolbar/assets/88400130/81c64f8f-7f47-40af-9285-9448ce18d94f)
![image](https://github.com/chrisgurney/obsidian-note-toolbar/assets/88400130/cd15125f-be63-4bb0-8f31-68524aff20e5)

**Desktop environment:**
 - OS: Windows 11
 - Obsidian version: 1.5.12
 - Note Toolbar version: 1.5.13 - beta

**Additional context**
If you disable the toolbar and reset the obsidian you need to click on calendar sidebar again to appear again -> after put toolbar on daily notes again.
My daily notes path has a year folder, like "daily/2024/notes", maybe thats something with it

**Comment by chrisgurney** [comment]
@CCerrer Interesting. Are you using any themes?

**Comment by CCerrer** [comment]
Tested rn disabling my theme and all snippets, remove the toolbar and reopen obsidian then adding toolbar again

Still bugged

**Comment by chrisgurney** [comment]
@CCerrer Also try removing the beta and updating to the latest via Community Plugins (had to skip a few versions so it's at `v1.5.20`).

**Comment by chrisgurney** [comment]
@CCerrer Can you provide a screenshot of your entire screen, so I can see how all the panes are positioned?

**Comment by chrisgurney** [comment]
@CCerrer OK, finally able to duplicate the issue, once I created a new note from the Calendar view. Will investigate.

**Comment by chrisgurney** [comment]
@CCerrer OK give the latest release a go: `v1.5.21`

**Comment by CCerrer** [comment]
@chrisgurney Wow that was really fast. Seems to be working well, thx

**Comment by chrisgurney** [comment]
@CCerrer Helps I'm unemployed at the moment. 😅

**Comment by chrisgurney** [comment]
@CCerrer Let me know if it happens again and I'll reopen the ticket.
