### ISSUE TITLE
Button Style doesn't work

### ISSUE THREAD

**Issue by viszzz** [chrisgurney/obsidian-note-toolbar#60]
**Description of the bug**

I tried to style the note toolbar buttons (not on the note toolbar callout) as buttons but it is not working. I tried in my own Vault, as well as with a sandbox Vault with just the plugin installed with both Default and Minimal theme. It works if the toolbar is a note callout.

**Steps to reproduce**

1. Opened a Sandbox Vault
2. Installed Note Toolbar
3. Create a new Toolbar
4. Styled the icons with "Button"
5. Added the toolbar to my notes

**Expected behavior**

The Icons are styled as buttons.

**Screenshots (if you think it will help)**

![image](https://github.com/chrisgurney/obsidian-note-toolbar/assets/53196439/ae18884b-3aa2-439e-b306-67ea854d57ab)
![image](https://github.com/chrisgurney/obsidian-note-toolbar/assets/53196439/70ef7dd5-bfd2-4ea4-9284-23a817443a5a)
![image](https://github.com/chrisgurney/obsidian-note-toolbar/assets/53196439/402e9158-7ac3-4217-9ed7-b90a8ae444bd)

**Desktop environment:**
 - OS: Windows 10
 - Obsidian version: 1.5.12
 - Note Toolbar version: 1.6.2

**Comment by chrisgurney** [comment]
@viszzz Sorry about that! 

Though I can't check at the moment, I think I know what's wrong. 

If I'm right, I can get a fix out today.

**Comment by chrisgurney** [comment]
@viszzz Fixed. Please update to `v1.6.3`

**Comment by viszzz** [comment]
It works like a charm now. Thanks a lot for such a quick fix!!
