### ISSUE TITLE
Fixed toolbar too big in height

### ISSUE THREAD

**Issue by Manu3232** [chrisgurney/obsidian-note-toolbar#63]
Hi, Its a very clever and useful plugin. thank you very much for creating it!
Just one quick suggestion: I think the height of the fixed toolbar is too big, both on mobile and desktop. Not a huge issue but saving space is important especially on mobile :)

![Screenshot 2024-05-05 005808](https://github.com/chrisgurney/obsidian-note-toolbar/assets/168284584/61abed63-e466-4b06-b6eb-7b654af84afa)

**Comment by chrisgurney** [comment]
@Manu3232 Thanks for the feedback!

A couple questions:

1. What theme are you using?
2. What device + OS did you take this screenshot on?

Thanks!

**Comment by chrisgurney** [comment]
@Manu3232 In the beta, I've added some options to adjust the padding and margins on toolbar items and the toolbar itself, via the Style Settings plugin. I've reorganized the settings to hopefully make it a little easier to use. Hope this helps!

![CleanShot 2024-05-05 at 15 18 23@2x](https://github.com/chrisgurney/obsidian-note-toolbar/assets/17337703/eb5eab1a-b8b6-4c17-9806-0c512a00ac02)

**Comment by chrisgurney** [comment]
Closing as the ability to adjust the size of the toolbar's padding and margins is now available.

**Comment by Manu3232** [comment]
> @Manu3232 Thanks for the feedback!
> 
> A couple questions:
> 
> 1. What theme are you using?
> 2. Are you using any CSS snippets worth noting?
> 3. What device + OS did you take this screenshot on?
> 
> Thanks!

Hi, not sure if my answers are still relevant since you added some customization options, but anyway:

1. Anuppuccin
2. Don´t think so.
3. Windows laptop

Thanks for your great plugin. It´s a real enhancement!
