### ISSUE TITLE
Feature Request: Ability to Exclude Toolbar Display in Specific Notes via Property Tag

### ISSUE THREAD

**Issue by fredjoe7** [chrisgurney/obsidian-note-toolbar#65]
i have the toolbar mapped to all the folders.

i want to just not show the toolbar in one particular note. 

Is it possible to exclude showing the toolbar in  particular notes only may be by adding a property in that note ?

**Comment by chrisgurney** [comment]
@fredjoe7 Yup! Just set the property to `none` in that note.

**Comment by fredjoe7** [comment]
thank you .. that works.

can the notetoolbar be made to autohide ?

**Comment by chrisgurney** [comment]
@fredjoe7 

> can the notetoolbar be made to autohide ?

Can you elaborate on what you specifically mean by this?

**Comment by fredjoe7** [comment]
When the mouse cursor is not positioned over the note toolbar, or when the note toolbar focus command is not activated, it should be set to auto-hide to prevent obstructing the view of the note. This feature would be particularly beneficial for desktop users with smaller displays, optimizing their workspace. This will be good for desktop devices, not mobile devices.


I used an this plugin called editing toolbar and its autohide features were useful.

https://github.com/PKM-er/obsidian-editing-toolbar

**Comment by chrisgurney** [comment]
Thanks for the explanation and pointer to the plugin.

That may be something to consider, for sure.

In the meantime, I've added an option to the context menu (in the beta) that lets you toggle between the top and properties positions, which can help to temporarily "hide" the toolbar if you're working in a long note (and are not using the "sticky" style).

**Comment by chrisgurney** [comment]
@fredjoe7 I'm closing this issue and have copied your suggestion about auto-hiding to this discussion:

https://github.com/chrisgurney/obsidian-note-toolbar/discussions/66

Thanks again for the suggestion!

**Comment by notDavid** [comment]
Hi there, is it also possible to exclude an entire folder ?

(i tried to map a folder to `none` but that didn't work)

**Comment by chrisgurney** [comment]
@notDavid Not at the moment. Depending on how an upcoming rewrite of the mapping rules works, this might be possible. Still determining how sophisticated it's going to be.

Thanks for letting me know you're interested in this feature!

**Comment by chrisgurney** [comment]
@notDavid FYI the ability to use more sophisticated rules is currently in development, and may provide the behaviour you were looking for (excluding a folder).

**Comment by notDavid** [comment]
@chrisgurney great! Thank you for the feedback :-)
