### ISSUE TITLE
Prop variables referencing links with aliases not resolving properly

### ISSUE THREAD

**Issue by chrisgurney** [chrisgurney/obsidian-note-toolbar#75]
**Description of the bug**

As uncovered in issue #73 by @moyf , properties that use links with aliases do not resolve to the actual note.

**Steps to reproduce**

1. Create a link to a note that exists in a prop, but also use an alias, e.g., `up: [[Welcome|Home]]`
2. Create and assign a toolbar to the note with an item with a prop variable that references the above prop e.g., `{{prop_up}}`
3. Click on the toolbar item

A new note with the contents of the link are created. Per the above example, `Welcome|Home`.

**Expected behavior**

The note `Welcome` should be opened.

**Screenshots (if you think it will help)**

![CleanShot 2024-05-20 at 09 19 20](https://github.com/chrisgurney/obsidian-note-toolbar/assets/17337703/d50ebee4-b751-44be-b814-90ea1077e69e)

**Desktop environment:**
 - OS: macOS
 - Obsidian version: 1.5.12 
 - Note Toolbar version: 1.7.28

**Mobile environment (if applicable to the issue):**

Not tested on mobile.

**Comment by chrisgurney** [comment]
@Moyf This should now be fixed in `v1.8.2`. Please give it a test and let me know if it works for you. Thanks!

**Comment by Moyf** [comment]
> @Moyf This should now be fixed in `v1.8.2`. Please give it a test and let me know if it works for you. Thanks!

YEEEEEEEES! Just tested it and it works now! Thank you!
