### ISSUE TITLE
Noisy console.log Not Behind this.DEBUG

### ISSUE THREAD

**Issue by mAAdhaTTah** [chrisgurney/obsidian-note-toolbar#8]
Nitty thing to complain about, but I was working on a DataView script and pulled up the console to test and I saw a lot of these logs from your plugin:

https://github.com/chrisgurney/obsidian-note-toolbar/blob/b047a80cb5919407460d91196e89de28e9cbb7d1/src/main.ts#L278

Everything else is behind a debug flag, so just wanted to flag (pun absolutely intended 😄) this one isn't.

Thanks for your work on this plugin!

**Comment by chrisgurney** [comment]
@mAAdhaTTah Thank you for the catch! They should all be gone in the next version. I've got `linting` on my todo list to setup and then suffer through. 😅

**Comment by chrisgurney** [comment]
Fixed in v1.3.1.

**Comment by chrisgurney** [comment]
Fixed in v1.3.1.
