### ISSUE TITLE
Cannot click note link with Control key (Hover Editor)

### ISSUE THREAD

**Issue by kmaustral** [chrisgurney/obsidian-note-toolbar#80]
**Description of the bug**
When I attempt to clink a note link holding down the control key (to open in new window), the note jumps up and down making it impossible to click the link. 

**Steps to reproduce**

1. Hold down control key and attempt to click note (in editing or reading view, with properties hidden or not)

**Expected behavior**
Open link in new window

**Theme links and CSS snippets (if applicable):**
_Themes and CSS snippets can affect the display of the toolbar. Include any being used here to help diagnose display issues._
None

**Plugin links (if applicable):**
_If you're using a specific plugin that isn't working with the toolbar, link it here._

**Desktop environment:**
 - OS: Windows
 - Obsidian version: 1.6.1
 - Note Toolbar version: 1.7.28

**Comment by kmaustral** [comment]
I've found that this instability occurs when the Hover Editor is enabled. It hadn't happened previously and it would be a shame to give up on that function..

**Comment by chrisgurney** [comment]
@kmaustral There's an issue for the Hover Editor conflict logged [here](https://github.com/chrisgurney/obsidian-note-toolbar/issues/14). 

See if setting the toolbar's `position = Top` to see if that does anything with the flickering. I think the issue only occurs with `position = Below Properties` at the moment.

**Comment by kmaustral** [comment]
Thanks, Chris. That seemed to work.

**Comment by chrisgurney** [comment]
Regarding the original issue:

> When I attempt to click a note link holding down the control key (to open in new window), the note jumps up and down making it impossible to click the link. 

What I believe is happening here is that I had to change toolbar items from links to spans (that act as links), in order to fix #19 which is particular to Android.

What I may end up doing is conditionally using spans only if the current platform is Android... but this will take some testing to make sure I don't introduce any major regressions.

**Comment by kmaustral** [comment]
That sounds like a good plan. Putting the toolbar above has fixed it for me
at the moment.

**Comment by chrisgurney** [comment]
I think there's still an issue to resolve here. 
See also: https://github.com/chrisgurney/obsidian-note-toolbar/discussions/81

**Comment by chrisgurney** [comment]
I've created a separate ticket for the issue around opening links with the Ctrl/Cmd key here: #91 

Closing this issue as it relates specifically to Hover Editor, and has a sort of workaround. Other conflicts with Hover Editor are tracked here: #14
