### ISSUE TITLE
[Bugs] Sticky rules doesn't work when using banners plugin

### ISSUE THREAD

**Issue by l2eused** [chrisgurney/obsidian-note-toolbar#87]
**Description of the bug**
when using banners plugin, when scroll down the toolbar doesn't sticky in top and disappear after certains scroll...

**Steps to reproduce**
1. download banners plugin 2.0.5-beta
2. download note toolbar 1.7.28
3. create a note with banner added
4. add ymal to apply note toolbar trigger (also add sticky rule)
5. note any contents (5+ paragraphs, >50 lines)
6. start scroll down page in source mode

**Expected behavior**
- it should be sticky as normal when banner plugin is disable

**Theme links and CSS snippets (if applicable):**
anuppuccin theme (this theme adding `--callout-content-padding` also...)

**Plugin links (if applicable):**
banner plugin https://github.com/noatpad/obsidian-banners

**Desktop environment:**
 - OS: windows 10
 - Obsidian version: 1.6.3
 - Note Toolbar version: 1.7.28

**Comment by chrisgurney** [comment]
@l2eused Thank you for reporting this issue! Will take a look when I get a chance.

**Comment by chrisgurney** [comment]
@l2eused Hello! I'm unable to reproduce this issue, at least on macOS. Can you provide:

1. Screenshot of your toolbar's configuration, particularly the Styles section.
2. Ideally video of the bug itself?

Here's how it's working for me, with the Anuppuccin theme, Banners 2.0.5-beta, and position = `Below Properties` with the `sticky` style, in source mode:

![CleanShot 2024-07-15 at 07 55 02](https://github.com/user-attachments/assets/bd5620fd-081c-4397-9e83-36f87e2f49ae)
